# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20170911_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='private',
            field=models.BooleanField(),
        ),
    ]
