# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20170911_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('api_request_count', models.IntegerField()),
            ],
            options={
                'db_table': 'ApiRequestCount',
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='api_request_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apirequestcount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Tenant'),
        ),
    ]
