# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 22:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20170912_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestcount',
            name='last_requested_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 12, 22, 3, 9, 378408)),
            preserve_default=False,
        ),
    ]
