# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-14 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20170912_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apirequestcount',
            name='api_request_count',
        ),
        migrations.RemoveField(
            model_name='apirequestcount',
            name='last_requested_on',
        ),
        migrations.AddField(
            model_name='apirequestcount',
            name='api_request',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apirequestcount',
            name='date',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
