# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-14 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20170914_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestcount',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apirequestcount',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
